In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_html('https://en.wikipedia.org/wiki/All-time_Olympic_Games_medal_table')
df[1]

                               Unnamed: 0_level_0 Summer Games  \
                                  Team (IOC code)            №
0                               Afghanistan (AFG)           14
1                                   Algeria (ALG)           13
2                                 Argentina (ARG)           24
3                                   Armenia (ARM)            6
4                         Australasia (ANZ) [ANZ]            2
5                       Australia (AUS) [AUS] [Z]           26
6                                   Austria (AUT)           27
7                                Azerbaijan (AZE)            6
8                                   Bahamas (BAH)           16
9                                   Bahrain (BRN)            9
10                           Barbados (BAR) [BAR]           12
11                                  Belarus (BLR)            6
12                                  Belgium (BEL)           26
13                                  Bermuda (BER)           18
14                        Bohemia (BOH) [BOH] [Z]            3
15                                 Botswana (BOT)           10
16                                   Brazil (BRA)           22
17                British West Indies (BWI) [BWI]            1
18                             Bulgaria (BUL) [H]           20
19                                  Burundi (BDI)            6
20                                 Cameroon (CMR)           14
21                                   Canada (CAN)           26
22                                Chile (CHI) [I]           23
23                              China (CHN) [CHN]           10
24                                 Colombia (COL)           19
25                               Costa Rica (CRC)           15
26                        Ivory Coast (CIV) [CIV]           13
27                                  Croatia (CRO)            7
28                                 Cuba (CUB) [Z]           20
29                                   Cyprus (CYP)           10
..                                            ...          ...
123                                   Sudan (SUD)           12
124                            Suriname (SUR) [E]           12
125                              Sweden (SWE) [Z]           27
126                             Switzerland (SUI)           28
127                                   Syria (SYR)           13
128             Chinese Taipei (TPE) [TPE] [TPE2]           14
129                              Tajikistan (TJK)            6
130                          Tanzania (TAN) [TAN]           13
131                                Thailand (THA)           16
132                                    Togo (TOG)           10
133                                   Tonga (TGA)            9
134               Trinidad and Tobago (TTO) [TTO]           17
135                                 Tunisia (TUN)           14
136                                  Turkey (TUR)           22
137                                  Uganda (UGA)           15
138                                 Ukraine (UKR)            6
139                    United Arab Emirates (UAE)            9
140       United States (USA) [P] [Q] [R] [Z] [F]           27
141                                 Uruguay (URU)           21
142                              Uzbekistan (UZB)            6
143                               Venezuela (VEN)           18
144                                 Vietnam (VIE)           15
145                          Virgin Islands (ISV)           12
146                        Yugoslavia (YUG) [YUG]           18
147                            Zambia (ZAM) [ZAM]           13
148                          Zimbabwe (ZIM) [ZIM]           13
149      Independent Olympic Athletes (IOA) [IOA]            3
150  Independent Olympic Participants (IOP) [IOP]            1
151                        Mixed team (ZZX) [ZZX]            3
152                                        Totals           28

                                                                     \
    Unnamed: 2_level_1 Unnamed: 3_level_1 Unnamed: 4_level_1  Total
0                    0                  0                  2      2
1                    5                  4                  8     17
2                   21                 25                 28     74
3                    2                  6                  6     14
4                    3                  4                  5     12
5                  147                163                187    497
6                   18                 33                 36     87
7                    7                 11                 24     42
8                    6                  2                  6     14
9                    2                  1                  0      3
10                   0                  0                  1      1
11                  12                 27                 39     78
12                  40                 53                 55    148
13                   0                  0                  1      1
14                   0                  1                  3      4
15                   0                  1                  0      1
16                  30                 36                 63    129
17                   0                  0                  2      2
18                  51                 87                 80    218
19                   1                  1                  0      2
20                   3                  1                  2      6
21                  64                102                136    302
22                   2                  7                  4     13
23                 224                167                155    546
24                   5                  9                 14     28
25                   1                  1                  2      4
26                   1                  1                  1      3
27                  11                 10                 12     33
28                  78                 68                 80    226
29                   0                  1                  0      1
..                 ...                ...                ...    ...
123                  0                  1                  0      1
124                  1                  0                  1      2
125                145                170                179    494
126                 50                 75                 67    192
127                  1                  1                  1      3
128                  5                  7                 12     24
129                  1                  1                  2      4
130                  0                  2                  0      2
131                  9                  8                 16     33
132                  0                  0                  1      1
133                  0                  1                  0      1
134                  3                  5                 11     19
135                  4                  2                  7     13
136                 39                 24                 28     91
137                  2                  3                  2      7
138                 34                 30                 56    120
139                  1                  0                  1      2
140               1022                795                705   2522
141                  2                  2                  6     10
142                  7                  6                 18     31
143                  2                  4                  9     15
144                  1                  3                  0      4
145                  0                  1                  0      1
146                 28                 31                 31     90
147                  0                  1                  1      2
148                  3                  4                  1      8
149                  1                  0                  1      2
150                  0                  1                  2      3
151                  8                  5                  4     17
152               5115               5081               5486  15682

    Winter Games                                                           \
               № Unnamed: 7_level_1 Unnamed: 8_level_1 Unnamed: 9_level_1
0              0                  0                  0                  0
1              3                  0                  0                  0
2             19                  0                  0                  0
3              7                  0                  0                  0
4              0                  0                  0                  0
5             19                  5                  5                  5
6             23                 64                 81                 87
7              6                  0                  0                  0
8              0                  0                  0                  0
9              0                  0                  0                  0
10             0                  0                  0                  0
11             7                  8                  5                  5
12            21                  1                  2                  3
13             8                  0                  0                  0
14             0                  0                  0                  0
15             0                  0                  0                  0
16             8                  0                  0                  0
17             0                  0                  0                  0
18            20                  1                  2                  3
19             0                  0                  0                  0
20             1                  0                  0                  0
21            23                 73                 64                 62
22            17                  0                  0                  0
23            11                 13                 28                 21
24             2                  0                  0                  0
25             6                  0                  0                  0
26             0                  0                  0                  0
27             8                  4                  6                  1
28             0                  0                  0                  0
29            11                  0                  0                  0
..           ...                ...                ...                ...
123            0                  0                  0                  0
124            0                  0                  0                  0
125           23                 57                 46                 55
126           23                 56                 45                 52
127            0                  0                  0                  0
128           12                  0                  0                  0
129            4                  0                  0                  0
130            0                  0                  0                  0
131            4                  0                  0                  0
132            2                  0                  0                  0
133            2                  0                  0                  0
134            3                  0                  0                  0
135            0                  0                  0                  0
136           17                  0                  0                  0
137            0                  0                  0                  0
138            7                  3                  1                  4
139            0                  0                  0                  0
140           23                105                112                 88
141            1                  0                  0                  0
142            7                  1                  0                  0
143            4                  0                  0                  0
144            0                  0                  0                  0
145            7                  0                  0                  0
146           16                  0                  3                  1
147            0                  0                  0                  0
148            1                  0                  0                  0
149            0                  0                  0                  0
150            0                  0                  0                  0
151            0                  0                  0                  0
152           23               1062               1058               1050

          Combined Total                                          \
    Total              № Unnamed: 12_level_1 Unnamed: 13_level_1
0       0             14                   0                   0
1       0             16                   5                   4
2       0             43                  21                  25
3       0             13                   2                   6
4       0              2                   3                   4
5      15             45                 152                 168
6     232             50                  82                 114
7       0             12                   7                  11
8       0             16                   6                   2
9       0              9                   2                   1
10      0             12                   0                   0
11     18             13                  20                  32
12      6             47                  41                  55
13      0             26                   0                   0
14      0              3                   0                   1
15      0             10                   0                   1
16      0             30                  30                  36
17      0              1                   0                   0
18      6             40                  52                  89
19      0              6                   1                   1
20      0             15                   3                   1
21    199             49                 137                 166
22      0             40                   2                   7
23     62             21                 237                 195
24      0             21                   5                   9
25      0             21                   1                   1
26      0             13                   1                   1
27     11             15                  15                  16
28      0             20                  78                  68
29      0             21                   0                   1
..    ...            ...                 ...                 ...
123     0             12                   0                   1
124     0             12                   1                   0
125   158             50                 202                 216
126   153             51                 106                 120
127     0             13                   1                   1
128     0             26                   5                   7
129     0             10                   1                   1
130     0             13                   0                   2
131     0             20                   9                   8
132     0             12                   0                   0
133     0             11                   0                   1
134     0             20                   3                   5
135     0             14                   4                   2
136     0             39                  39                  24
137     0             15                   2                   3
138     8             13                  37                  31
139     0              9                   1                   0
140   305             50                1127                 907
141     0             22                   2                   2
142     1             13                   8                   6
143     0             22                   2                   4
144     0             15                   1                   3
145     0             19                   0                   1
146     4             34                  28                  34
147     0             13                   0                   1
148     0             14                   3                   4
149     0              3                   1                   0
150     0              1                   0                   1
151     0              3                   8                   5
152  3170             51                6177                6139


    Unnamed: 14_level_1  Total
0                     2      2
1                     8     17
2                    28     74
3                     6     14
4                     5     12
5                   192    512
6                   123    319
7                    24     42
8                     6     14
9                     0      3
10                    1      1
11                   44     96
12                   58    154
13                    1      1
14                    3      4
15                    0      1
16                   63    129
17                    2      2
18                   83    224
19                    0      2
20                    2      6
21                  198    501
22                    4     13
23                  176    608
24                   14     28
25                    2      4
26                    1      3
27                   13     44
28                   80    226
29                    0      1
..                  ...    ...
123                   0      1
124                   1      2
125                 234    652
126                 119    345
127                   1      3
128                  12     24
129                   2      4
130                   0      2
131                  16     33
132                   1      1
133                   0      1
134                  11     19
135                   7     13
136                  28     91
137                   2      7
138                  60    128
139                   1      2
140                 793   2827
141                   6     10
142                  18     32
143                   9     15
144                   0      4
145                   0      1
146                  32     94
147                   1      2
148                   1      8
149                   1      2
150                   2      3
151                   4     17
152                6536  18852

[153 rows x 16 columns]

In [3]:
df = pd.read_html('https://en.wikipedia.org/wiki/All-time_Olympic_Games_medal_table', header = 0, index_col = 0)
df[1]

,Summer Games,Summer Games.1,Summer Games.2,Summer Games.3,Summer Games.4,Winter Games,Winter Games.1,Winter Games.2,Winter Games.3,Winter Games.4,Combined Total,Combined Total.1,Combined Total.2,Combined Total.3,Combined Total.4
Team (IOC code),№,NaN,NaN,NaN,Total,№,NaN,NaN,NaN,Total,№,NaN,NaN,NaN,Total
Afghanistan (AFG),14,0.0,0.0,2.0,2,0,0.0,0.0,0.0,0,14,0.0,0.0,2.0,2
Algeria (ALG),13,5.0,4.0,8.0,17,3,0.0,0.0,0.0,0,16,5.0,4.0,8.0,17
Argentina (ARG),24,21.0,25.0,28.0,74,19,0.0,0.0,0.0,0,43,21.0,25.0,28.0,74
Armenia (ARM),6,2.0,6.0,6.0,14,7,0.0,0.0,0.0,0,13,2.0,6.0,6.0,14
Australasia (ANZ) [ANZ],2,3.0,4.0,5.0,12,0,0.0,0.0,0.0,0,2,3.0,4.0,5.0,12
Australia (AUS) [AUS] [Z],26,147.0,163.0,187.0,497,19,5.0,5.0,5.0,15,45,152.0,168.0,192.0,512
Austria (AUT),27,18.0,33.0,36.0,87,23,64.0,81.0,87.0,232,50,82.0,114.0,123.0,319
Azerbaijan (AZE),6,7.0,11.0,24.0,42,6,0.0,0.0,0.0,0,12,7.0,11.0,24.0,42
Bahamas (BAH),16,6.0,2.0,6.0,14,0,0.0,0.0,0.0,0,16,6.0,2.0,6.0,14
Bahrain (BRN),9,2.0,1.0,0.0,3,0,0.0,0.0,0.0,0,9,2.0,1.0,0.0,3
Barbados (BAR) [BAR],12,0.0,0.0,1.0,1,0,0.0,0.0,0.0,0,12,0.0,0.0,1.0,1
Belarus (BLR),6,12.0,27.0,39.0,78,7,8.0,5.0,5.0,18,13,20.0,32.0,44.0,96
Belgium (BEL),26,40.0,53.0,55.0,148,21,1.0,2.0,3.0,6,47,41.0,55.0,58.0,154
Bermuda (BER),18,0.0,0.0,1.0,1,8,0.0,0.0,0.0,0,26,0.0,0.0,1.0,1
Bohemia (BOH) [BOH] [Z],3,0.0,1.0,3.0,4,0,0.0,0.0,0.0,0,3,0.0,1.0,3.0,4
Botswana (BOT),10,0.0,1.0,0.0,1,0,0.0,0.0,0.0,0,10,0.0,1.0,0.0,1
Brazil (BRA),22,30.0,36.0,63.0,129,8,0.0,0.0,0.0,0,30,30.0,36.0,63.0,129
British West Indies (BWI) [BWI],1,0.0,0.0,2.0,2,0,0.0,0.0,0.0,0,1,0.0,0.0,2.0,2
Bulgaria (BUL) [H],20,51.0,87.0,80.0,218,20,1.0,2.0,3.0,6,40,52.0,89.0,83.0,224
Burundi (BDI),6,1.0,1.0,0.0,2,0,0.0,0.0,0.0,0,6,1.0,1.0,0.0,2
Cameroon (CMR),14,3.0,1.0,2.0,6,1,0.0,0.0,0.0,0,15,3.0,1.0,2.0,6
Canada (CAN),26,64.0,102.0,136.0,302,23,73.0,64.0,62.0,199,49,137.0,166.0,198.0,501
Chile (CHI) [I],23,2.0,7.0,4.0,13,17,0.0,0.0,0.0,0,40,2.0,7.0,4.0,13
China (CHN) [CHN],10,224.0,167.0,155.0,546,11,13.0,28.0,21.0,62,21,237.0,195.0,176.0,608
Colombia (COL),19,5.0,9.0,14.0,28,2,0.0,0.0,0.0,0,21,5.0,9.0,14.0,28
Costa Rica (CRC),15,1.0,1.0,2.0,4,6,0.0,0.0,0.0,0,21,1.0,1.0,2.0,4
Ivory Coast (CIV) [CIV],13,1.0,1.0,1.0,3,0,0.0,0.0,0.0,0,13,1.0,1.0,1.0,3
Croatia (CRO),7,11.0,10.0,12.0,33,8,4.0,6.0,1.0,11,15,15.0,16.0,13.0,44
Cuba (CUB) [Z],20,78.0,68.0,80.0,226,0,0.0,0.0,0.0,0,20,78.0,68.0,80.0,226
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Sudan (SUD),12,0.0,1.0,0.0,1,0,0.0,0.0,0.0,0,12,0.0,1.0,0.0,1
Suriname (SUR) [E],12,1.0,0.0,1.0,2,0,0.0,0.0,0.0,0,12,1.0,0.0,1.0,2
Sweden (SWE) [Z],27,145.0,170.0,179.0,494,23,57.0,46.0,55.0,158,50,202.0,216.0,234.0,652
Switzerland (SUI),28,50.0,75.0,67.0,192,23,56.0,45.0,52.0,153,51,106.0,120.0,119.0,345
Syria (SYR),13,1.0,1.0,1.0,3,0,0.0,0.0,0.0,0,13,1.0,1.0,1.0,3
Chinese Taipei (TPE) [TPE] [TPE2],14,5.0,7.0,12.0,24,12,0.0,0.0,0.0,0,26,5.0,7.0,12.0,24
Tajikistan (TJK),6,1.0,1.0,2.0,4,4,0.0,0.0,0.0,0,10,1.0,1.0,2.0,4
Tanzania (TAN) [TAN],13,0.0,2.0,0.0,2,0,0.0,0.0,0.0,0,13,0.0,2.0,0.0,2
Thailand (THA),16,9.0,8.0,16.0,33,4,0.0,0.0,0.0,0,20,9.0,8.0,16.0,33
Togo (TOG),10,0.0,0.0,1.0,1,2,0.0,0.0,0.0,0,12,0.0,0.0,1.0,1
Tonga (TGA),9,0.0,1.0,0.0,1,2,0.0,0.0,0.0,0,11,0.0,1.0,0.0,1
Trinidad and Tobago (TTO) [TTO],17,3.0,5.0,11.0,19,3,0.0,0.0,0.0,0,20,3.0,5.0,11.0,19
Tunisia (TUN),14,4.0,2.0,7.0,13,0,0.0,0.0,0.0,0,14,4.0,2.0,7.0,13
Turkey (TUR),22,39.0,24.0,28.0,91,17,0.0,0.0,0.0,0,39,39.0,24.0,28.0,91
Uganda (UGA),15,2.0,3.0,2.0,7,0,0.0,0.0,0.0,0,15,2.0,3.0,2.0,7
Ukraine (UKR),6,34.0,30.0,56.0,120,7,3.0,1.0,4.0,8,13,37.0,31.0,60.0,128
United Arab Emirates (UAE),9,1.0,0.0,1.0,2,0,0.0,0.0,0.0,0,9,1.0,0.0,1.0,2
United States (USA) [P] [Q] [R] [Z] [F],27,1022.0,795.0,705.0,2522,23,105.0,112.0,88.0,305,50,1127.0,907.0,793.0,2827
Uruguay (URU),21,2.0,2.0,6.0,10,1,0.0,0.0,0.0,0,22,2.0,2.0,6.0,10
Uzbekistan (UZB),6,7.0,6.0,18.0,31,7,1.0,0.0,0.0,1,13,8.0,6.0,18.0,32
Venezuela (VEN),18,2.0,4.0,9.0,15,4,0.0,0.0,0.0,0,22,2.0,4.0,9.0,15
Vietnam (VIE),15,1.0,3.0,0.0,4,0,0.0,0.0,0.0,0,15,1.0,3.0,0.0,4
Virgin Islands (ISV),12,0.0,1.0,0.0,1,7,0.0,0.0,0.0,0,19,0.0,1.0,0.0,1
Yugoslavia (YUG) [YUG],18,28.0,31.0,31.0,90,16,0.0,3.0,1.0,4,34,28.0,34.0,32.0,94
Zambia (ZAM) [ZAM],13,0.0,1.0,1.0,2,0,0.0,0.0,0.0,0,13,0.0,1.0,1.0,2
Zimbabwe (ZIM) [ZIM],13,3.0,4.0,1.0,8,1,0.0,0.0,0.0,0,14,3.0,4.0,1.0,8
Independent Olympic Athletes (IOA) [IOA],3,1.0,0.0,1.0,2,0,0.0,0.0,0.0,0,3,1.0,0.0,1.0,2
Independent Olympic Participants (IOP) [IOP],1,0.0,1.0,2.0,3,0,0.0,0.0,0.0,0,1,0.0,1.0,2.0,3
Mixed team (ZZX) [ZZX],3,8.0,5.0,4.0,17,0,0.0,0.0,0.0,0,3,8.0,5.0,4.0,17
Totals,28,5115.0,5081.0,5486.0,15682,23,1062.0,1058.0,1050.0,3170,51,6177.0,6139.0,6536.0,18852

In [4]:
summer = df[1].iloc[:, :5]
summer

,Summer Games,Summer Games.1,Summer Games.2,Summer Games.3,Summer Games.4
Team (IOC code),№,NaN,NaN,NaN,Total
Afghanistan (AFG),14,0.0,0.0,2.0,2
Algeria (ALG),13,5.0,4.0,8.0,17
Argentina (ARG),24,21.0,25.0,28.0,74
Armenia (ARM),6,2.0,6.0,6.0,14
Australasia (ANZ) [ANZ],2,3.0,4.0,5.0,12
Australia (AUS) [AUS] [Z],26,147.0,163.0,187.0,497
Austria (AUT),27,18.0,33.0,36.0,87
Azerbaijan (AZE),6,7.0,11.0,24.0,42
Bahamas (BAH),16,6.0,2.0,6.0,14
Bahrain (BRN),9,2.0,1.0,0.0,3
Barbados (BAR) [BAR],12,0.0,0.0,1.0,1
Belarus (BLR),6,12.0,27.0,39.0,78
Belgium (BEL),26,40.0,53.0,55.0,148
Bermuda (BER),18,0.0,0.0,1.0,1
Bohemia (BOH) [BOH] [Z],3,0.0,1.0,3.0,4
Botswana (BOT),10,0.0,1.0,0.0,1
Brazil (BRA),22,30.0,36.0,63.0,129
British West Indies (BWI) [BWI],1,0.0,0.0,2.0,2
Bulgaria (BUL) [H],20,51.0,87.0,80.0,218
Burundi (BDI),6,1.0,1.0,0.0,2
Cameroon (CMR),14,3.0,1.0,2.0,6
Canada (CAN),26,64.0,102.0,136.0,302
Chile (CHI) [I],23,2.0,7.0,4.0,13
China (CHN) [CHN],10,224.0,167.0,155.0,546
Colombia (COL),19,5.0,9.0,14.0,28
Costa Rica (CRC),15,1.0,1.0,2.0,4
Ivory Coast (CIV) [CIV],13,1.0,1.0,1.0,3
Croatia (CRO),7,11.0,10.0,12.0,33
Cuba (CUB) [Z],20,78.0,68.0,80.0,226
...,...,...,...,...,...
Sudan (SUD),12,0.0,1.0,0.0,1
Suriname (SUR) [E],12,1.0,0.0,1.0,2
Sweden (SWE) [Z],27,145.0,170.0,179.0,494
Switzerland (SUI),28,50.0,75.0,67.0,192
Syria (SYR),13,1.0,1.0,1.0,3
Chinese Taipei (TPE) [TPE] [TPE2],14,5.0,7.0,12.0,24
Tajikistan (TJK),6,1.0,1.0,2.0,4
Tanzania (TAN) [TAN],13,0.0,2.0,0.0,2
Thailand (THA),16,9.0,8.0,16.0,33
Togo (TOG),10,0.0,0.0,1.0,1
Tonga (TGA),9,0.0,1.0,0.0,1
Trinidad and Tobago (TTO) [TTO],17,3.0,5.0,11.0,19
Tunisia (TUN),14,4.0,2.0,7.0,13
Turkey (TUR),22,39.0,24.0,28.0,91
Uganda (UGA),15,2.0,3.0,2.0,7
Ukraine (UKR),6,34.0,30.0,56.0,120
United Arab Emirates (UAE),9,1.0,0.0,1.0,2
United States (USA) [P] [Q] [R] [Z] [F],27,1022.0,795.0,705.0,2522
Uruguay (URU),21,2.0,2.0,6.0,10
Uzbekistan (UZB),6,7.0,6.0,18.0,31
Venezuela (VEN),18,2.0,4.0,9.0,15
Vietnam (VIE),15,1.0,3.0,0.0,4
Virgin Islands (ISV),12,0.0,1.0,0.0,1
Yugoslavia (YUG) [YUG],18,28.0,31.0,31.0,90
Zambia (ZAM) [ZAM],13,0.0,1.0,1.0,2
Zimbabwe (ZIM) [ZIM],13,3.0,4.0,1.0,8
Independent Olympic Athletes (IOA) [IOA],3,1.0,0.0,1.0,2
Independent Olympic Participants (IOP) [IOP],1,0.0,1.0,2.0,3
Mixed team (ZZX) [ZZX],3,8.0,5.0,4.0,17
Totals,28,5115.0,5081.0,5486.0,15682

In [5]:
summer.columns = ['경기수', '금', '은', '동', '계']
print(summer)

                                             경기수       금       은       동  \
Team (IOC code)                                №     NaN     NaN     NaN
Afghanistan (AFG)                             14     0.0     0.0     2.0
Algeria (ALG)                                 13     5.0     4.0     8.0
Argentina (ARG)                               24    21.0    25.0    28.0
Armenia (ARM)                                  6     2.0     6.0     6.0
Australasia (ANZ) [ANZ]                        2     3.0     4.0     5.0
Australia (AUS) [AUS] [Z]                     26   147.0   163.0   187.0
Austria (AUT)                                 27    18.0    33.0    36.0
Azerbaijan (AZE)                               6     7.0    11.0    24.0
Bahamas (BAH)                                 16     6.0     2.0     6.0
Bahrain (BRN)                                  9     2.0     1.0     0.0
Barbados (BAR) [BAR]                          12     0.0     0.0     1.0
Belarus (BLR)                                  6    12.0    27.0    39.0
Belgium (BEL)                                 26    40.0    53.0    55.0
Bermuda (BER)                                 18     0.0     0.0     1.0
Bohemia (BOH) [BOH] [Z]                        3     0.0     1.0     3.0
Botswana (BOT)                                10     0.0     1.0     0.0
Brazil (BRA)                                  22    30.0    36.0    63.0
British West Indies (BWI) [BWI]                1     0.0     0.0     2.0
Bulgaria (BUL) [H]                            20    51.0    87.0    80.0
Burundi (BDI)                                  6     1.0     1.0     0.0
Cameroon (CMR)                                14     3.0     1.0     2.0
Canada (CAN)                                  26    64.0   102.0   136.0
Chile (CHI) [I]                               23     2.0     7.0     4.0
China (CHN) [CHN]                             10   224.0   167.0   155.0
Colombia (COL)                                19     5.0     9.0    14.0
Costa Rica (CRC)                              15     1.0     1.0     2.0
Ivory Coast (CIV) [CIV]                       13     1.0     1.0     1.0
Croatia (CRO)                                  7    11.0    10.0    12.0
Cuba (CUB) [Z]                                20    78.0    68.0    80.0
...                                           ..     ...     ...     ...
Sudan (SUD)                                   12     0.0     1.0     0.0
Suriname (SUR) [E]                            12     1.0     0.0     1.0
Sweden (SWE) [Z]                              27   145.0   170.0   179.0
Switzerland (SUI)                             28    50.0    75.0    67.0
Syria (SYR)                                   13     1.0     1.0     1.0
Chinese Taipei (TPE) [TPE] [TPE2]             14     5.0     7.0    12.0
Tajikistan (TJK)                               6     1.0     1.0     2.0
Tanzania (TAN) [TAN]                          13     0.0     2.0     0.0
Thailand (THA)                                16     9.0     8.0    16.0
Togo (TOG)                                    10     0.0     0.0     1.0
Tonga (TGA)                                    9     0.0     1.0     0.0
Trinidad and Tobago (TTO) [TTO]               17     3.0     5.0    11.0
Tunisia (TUN)                                 14     4.0     2.0     7.0
Turkey (TUR)                                  22    39.0    24.0    28.0
Uganda (UGA)                                  15     2.0     3.0     2.0
Ukraine (UKR)                                  6    34.0    30.0    56.0
United Arab Emirates (UAE)                     9     1.0     0.0     1.0
United States (USA) [P] [Q] [R] [Z] [F]       27  1022.0   795.0   705.0
Uruguay (URU)                                 21     2.0     2.0     6.0
Uzbekistan (UZB)                               6     7.0     6.0    18.0
Venezuela (VEN)                               18     2.0     4.0     9.0
Vietnam (VIE)                                 15     1.0     3.0     0.0
Virgin Islands (ISV)                          12     0.0     1.0     0.0
Yugoslavia (YUG) [YUG]                        18    28.0    31.0    31.0
Zambia (ZAM) [ZAM]                            13     0.0     1.0     1.0
Zimbabwe (ZIM) [ZIM]                          13     3.0     4.0     1.0
Independent Olympic Athletes (IOA) [IOA]       3     1.0     0.0     1.0
Independent Olympic Participants (IOP) [IOP]   1     0.0     1.0     2.0
Mixed team (ZZX) [ZZX]                         3     8.0     5.0     4.0
Totals                                        28  5115.0  5081.0  5486.0

                                                  계
Team (IOC code)                               Total
Afghanistan (AFG)                                 2
Algeria (ALG)                                    17
Argentina (ARG)                                  74
Armenia (ARM)                                    14
Australasia (ANZ) [ANZ]                          12
Australia (AUS) [AUS] [Z]                       497
Austria (AUT)                                    87
Azerbaijan (AZE)                                 42
Bahamas (BAH)                                    14
Bahrain (BRN)                                     3
Barbados (BAR) [BAR]                              1
Belarus (BLR)                                    78
Belgium (BEL)                                   148
Bermuda (BER)                                     1
Bohemia (BOH) [BOH] [Z]                           4
Botswana (BOT)                                    1
Brazil (BRA)                                    129
British West Indies (BWI) [BWI]                   2
Bulgaria (BUL) [H]                              218
Burundi (BDI)                                     2
Cameroon (CMR)                                    6
Canada (CAN)                                    302
Chile (CHI) [I]                                  13
China (CHN) [CHN]                               546
Colombia (COL)                                   28
Costa Rica (CRC)                                  4
Ivory Coast (CIV) [CIV]                           3
Croatia (CRO)                                    33
Cuba (CUB) [Z]                                  226
...                                             ...
Sudan (SUD)                                       1
Suriname (SUR) [E]                                2
Sweden (SWE) [Z]                                494
Switzerland (SUI)                               192
Syria (SYR)                                       3
Chinese Taipei (TPE) [TPE] [TPE2]                24
Tajikistan (TJK)                                  4
Tanzania (TAN) [TAN]                              2
Thailand (THA)                                   33
Togo (TOG)                                        1
Tonga (TGA)                                       1
Trinidad and Tobago (TTO) [TTO]                  19
Tunisia (TUN)                                    13
Turkey (TUR)                                     91
Uganda (UGA)                                      7
Ukraine (UKR)                                   120
United Arab Emirates (UAE)                        2
United States (USA) [P] [Q] [R] [Z] [F]        2522
Uruguay (URU)                                    10
Uzbekistan (UZB)                                 31
Venezuela (VEN)                                  15
Vietnam (VIE)                                     4
Virgin Islands (ISV)                              1
Yugoslavia (YUG) [YUG]                           90
Zambia (ZAM) [ZAM]                                2
Zimbabwe (ZIM) [ZIM]                              8
Independent Olympic Athletes (IOA) [IOA]          2
Independent Olympic Participants (IOP) [IOP]      3
Mixed team (ZZX) [ZZX]                           17
Totals                                        15682

[154 rows x 5 columns]

In [6]:
df = pd.read_html('https://en.wikipedia.org/wiki/All-time_Olympic_Games_medal_table', header=0, index_col=0)
summer = df[1].iloc[:, :5]
summer.columns = ['경기수', '금', '은', '동', '계']
print(summer.sort_values('금', ascending=False))

                                         경기수       금       은       동      계
Totals                                    28  5115.0  5081.0  5486.0  15682
United States (USA) [P] [Q] [R] [Z] [F]   27  1022.0   795.0   705.0   2522
Soviet Union (URS) [URS]                   9   395.0   319.0   296.0   1010
Great Britain (GBR) [GBR] [Z]             28   263.0   295.0   293.0    851
China (CHN) [CHN]                         10   224.0   167.0   155.0    546
France (FRA) [O] [P] [Z]                  28   212.0   241.0   263.0    716
Italy (ITA) [M] [S]                       28   206.0   178.0   193.0    577
Germany (GER) [GER] [Z]                   16   191.0   194.0   230.0    615
Hungary (HUN)                             26   175.0   147.0   169.0    491
East Germany (GDR) [GDR]                   5   153.0   129.0   127.0    409
Russia (RUS) [RUS]                         6   148.0   125.0   153.0    426
Australia (AUS) [AUS] [Z]                 26   147.0   163.0   187.0    497
Sweden (SWE) [Z]                          27   145.0   170.0   179.0    494
Japan (JPN)                               22   142.0   136.0   161.0    439
Finland (FIN)                             25   101.0    85.0   117.0    303
South Korea (KOR)                         17    90.0    87.0    90.0    267
Romania (ROU)                             21    89.0    95.0   122.0    306
Netherlands (NED) [Z]                     26    85.0    92.0   108.0    285
Cuba (CUB) [Z]                            20    78.0    68.0    80.0    226
Poland (POL)                              21    68.0    84.0   132.0    284
Canada (CAN)                              26    64.0   102.0   136.0    302
Norway (NOR) [Q]                          25    56.0    49.0    47.0    152
West Germany (FRG) [FRG]                   5    56.0    67.0    81.0    204
Bulgaria (BUL) [H]                        20    51.0    87.0    80.0    218
Switzerland (SUI)                         28    50.0    75.0    67.0    192
Czechoslovakia (TCH) [TCH]                16    49.0    49.0    45.0    143
New Zealand (NZL) [NZL]                   23    46.0    27.0    44.0    117
Spain (ESP) [Z]                           23    45.0    64.0    41.0    150
Denmark (DEN) [Z]                         27    45.0    74.0    75.0    194
Unified Team (EUN) [EUN]                   1    45.0    38.0    29.0    112
...                                       ..     ...     ...     ...    ...
Cyprus (CYP)                              10     0.0     1.0     0.0      1
Liechtenstein (LIE)                       17     0.0     0.0     0.0      0
Kuwait (KUW)                              12     0.0     0.0     2.0      2
Macedonia (MKD)                            6     0.0     0.0     1.0      1
Malaysia (MAS) [MAS]                      13     0.0     7.0     4.0     11
Mauritius (MRI)                            9     0.0     0.0     1.0      1
Moldova (MDA)                              6     0.0     2.0     3.0      5
Montenegro (MNE)                           3     0.0     1.0     0.0      1
Namibia (NAM)                              7     0.0     4.0     0.0      4
Netherlands Antilles (AHO) [AHO] [I]      13     0.0     1.0     0.0      1
Iraq (IRQ)                                14     0.0     0.0     1.0      1
Niger (NIG)                               12     0.0     1.0     1.0      2
Iceland (ISL)                             20     0.0     2.0     2.0      4
Haiti (HAI) [J]                           15     0.0     1.0     1.0      2
Paraguay (PAR)                            12     0.0     1.0     0.0      1
Philippines (PHI)                         21     0.0     3.0     7.0     10
Guyana (GUY) [GUY]                        17     0.0     0.0     1.0      1
Guatemala (GUA)                           14     0.0     1.0     0.0      1
Qatar (QAT)                                9     0.0     1.0     4.0      5
Ghana (GHA) [GHA]                         14     0.0     1.0     3.0      4
Gabon (GAB)                               10     0.0     1.0     0.0      1
Olympic Athletes from Russia (OAR) [OAR]   0     0.0     0.0     0.0      0
Saudi Arabia (KSA)                        11     0.0     1.0     2.0      3
Samoa (SAM)                                9     0.0     1.0     0.0      1
Lebanon (LIB)                             17     0.0     2.0     2.0      4
Eritrea (ERI)                              5     0.0     0.0     1.0      1
Serbia and Montenegro (SCG) [SCG]          1     0.0     2.0     0.0      2
Djibouti (DJI) [B]                         8     0.0     0.0     1.0      1
Afghanistan (AFG)                         14     0.0     0.0     2.0      2
Team (IOC code)                            №     NaN     NaN     NaN  Total

[154 rows x 5 columns]

In [7]:
summer.to_excel('하계올림픽메달.xlsx')

In [8]:
index = pd.date_range('1/1/2000', periods=8)
print(index)

DatetimeIndex(['2000-01-01', '2000-01-02', '2000-01-03', '2000-01-04',
               '2000-01-05', '2000-01-06', '2000-01-07', '2000-01-08'],
              dtype='datetime64[ns]', freq='D')

In [9]:
df = pd.DataFrame(np.random.rand(8, 3), index=index, columns=list('ABC'))
df

                   A         B         C
2000-01-01  0.103672  0.716269  0.908572
2000-01-02  0.574507  0.905576  0.071653
2000-01-03  0.403691  0.854197  0.809829
2000-01-04  0.649898  0.375989  0.771619
2000-01-05  0.677976  0.159781  0.479603
2000-01-06  0.063919  0.790315  0.861042
2000-01-07  0.223495  0.728749  0.590489
2000-01-08  0.241714  0.739901  0.061603

In [10]:
index = pd.date_range('1/1/2000', periods=8)
df = pd.DataFrame(np.random.rand(8, 3), index=index, columns=list('ABC'))
print(df['B'])

2000-01-01    0.505688
2000-01-02    0.759044
2000-01-03    0.784577
2000-01-04    0.834210
2000-01-05    0.351571
2000-01-06    0.034917
2000-01-07    0.458708
2000-01-08    0.341074
Freq: D, Name: B, dtype: float64

In [11]:
index = pd.date_range('1/1/2000', periods=8)
df = pd.DataFrame(np.random.rand(8, 3), index=index, columns=list('ABC'))
print(df['B'] > 0.4)

2000-01-01    False
2000-01-02     True
2000-01-03     True
2000-01-04     True
2000-01-05     True
2000-01-06     True
2000-01-07     True
2000-01-08    False
Freq: D, Name: B, dtype: bool

In [12]:
df2 = df[df['B'] > 0.4]
df2

                   A         B         C
2000-01-02  0.451465  0.681186  0.852444
2000-01-03  0.051616  0.759358  0.620292
2000-01-04  0.011321  0.913739  0.152423
2000-01-05  0.317001  0.923020  0.409092
2000-01-06  0.283228  0.916682  0.384825
2000-01-07  0.264019  0.562225  0.602733

In [13]:
index = pd.date_range('1/1/2000', periods=8)
df = pd.DataFrame(np.random.rand(8, 3), index=index, columns=list('ABC'))
df['D'] = df['A'] / df['B']
df

                   A         B         C          D
2000-01-01  0.208825  0.880694  0.965237   0.237114
2000-01-02  0.462096  0.704037  0.086243   0.656352
2000-01-03  0.346423  0.524493  0.010849   0.660491
2000-01-04  0.732647  0.184392  0.826941   3.973317
2000-01-05  0.789929  0.203126  0.285688   3.888871
2000-01-06  0.334100  0.847281  0.785882   0.394321
2000-01-07  0.369509  0.813587  0.263642   0.454172
2000-01-08  0.756306  0.029990  0.561193  25.218967

In [14]:
index = pd.date_range('1/1/2000', periods=8)
df = pd.DataFrame(np.random.rand(8, 3), index = index, columns=list('ABC'))

df['D'] = df['A'] / df['B']
df['E'] = np.sum(df, axis=1)
df.head()

                   A         B         C         D         E
2000-01-01  0.059273  0.957462  0.489676  0.061906  1.568318
2000-01-02  0.793573  0.441275  0.329908  1.798364  3.363120
2000-01-03  0.130674  0.568878  0.903853  0.229704  1.833108
2000-01-04  0.094392  0.951536  0.745399  0.099199  1.890526
2000-01-05  0.492219  0.738393  0.623901  0.666608  2.521122

In [15]:
index = pd.date_range('1/1/2000', periods=8)
df = pd.DataFrame(np.random.rand(8, 3), index=index, columns=list('ABC'))
df['D'] = df['A'] / df['B']
df['E'] = np.sum(df, axis=1)
df = df.sub(df['A'], axis=0)
df.head()

              A         B         C         D         E
2000-01-01  0.0 -0.455482 -0.486370  1.067856  2.878980
2000-01-02  0.0 -0.542231  0.143483  3.632683  5.348043
2000-01-03  0.0 -0.317547 -0.696744  0.865197  2.242050
2000-01-04  0.0 -0.431068 -0.065413  1.205751  3.236327
2000-01-05  0.0  0.440219 -0.072418  0.091797  0.802305

In [16]:
index = pd.date_range('1/1/2000', periods=8)
df = pd.DataFrame(np.random.rand(8, 3), index=index, columns=list('ABC'))
df['D'] = df['A'] / df['B']
df['E'] = np.sum(df, axis=1)

df = df.sub(df['A'], axis = 0)
df = df.div(df['C'], axis = 0)

df.to_csv('test.csv')
df.head()

              A         B    C          D          E
2000-01-01  0.0  1.474579  1.0   0.016862  10.892808
2000-01-02 -0.0  0.642892  1.0  -1.321780  -3.719980
2000-01-03 -0.0  0.987117  1.0 -10.765304 -27.763156
2000-01-04 -0.0 -0.228833  1.0  -2.386811 -14.641531
2000-01-05 -0.0 -1.171817  1.0  -0.469518 -18.714540